//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressApp.WpfUI.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgressApp.WpfUI.Localization.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProgressApp .
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Password.
        /// </summary>
        public static string Btn_ChangePassword {
            get {
                return ResourceManager.GetString("Btn_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Btn_SaveDay {
            get {
                return ResourceManager.GetString("Btn_SaveDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set password.
        /// </summary>
        public static string Btn_SetPassword {
            get {
                return ResourceManager.GetString("Btn_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string DataGrid_Date {
            get {
                return ResourceManager.GetString("DataGrid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result.
        /// </summary>
        public static string DataGrid_Result {
            get {
                return ResourceManager.GetString("DataGrid_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect password. Please try again.
        /// </summary>
        public static string Error_IncorrectPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to change password. Check logs.
        /// </summary>
        public static string Msg_ChangePasswordFailedError {
            get {
                return ResourceManager.GetString("Msg_ChangePasswordFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database save error. Check logs.
        /// </summary>
        public static string Msg_DbSaveWhileImportError {
            get {
                return ResourceManager.GetString("Msg_DbSaveWhileImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description cannot be empty!.
        /// </summary>
        public static string Msg_DescriptionEmpty {
            get {
                return ResourceManager.GetString("Msg_DescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate records found. Each record must be unique..
        /// </summary>
        public static string Msg_DuplicateRecordsImportError {
            get {
                return ResourceManager.GetString("Msg_DuplicateRecordsImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error during import: The description cannot be empty. Line: {0}.
        /// </summary>
        public static string Msg_EmptyDescriptionImportError {
            get {
                return ResourceManager.GetString("Msg_EmptyDescriptionImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No records to import.
        /// </summary>
        public static string Msg_EntriesIsEmptyImportError {
            get {
                return ResourceManager.GetString("Msg_EntriesIsEmptyImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database access error. Check logs.
        /// </summary>
        public static string Msg_ErrorDbAccessFailed {
            get {
                return ResourceManager.GetString("Msg_ErrorDbAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data loading error. Check log file.
        /// </summary>
        public static string Msg_ErrorLoadingData {
            get {
                return ResourceManager.GetString("Msg_ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to load settings: “{0}”. Please try again or check the database.
        /// </summary>
        public static string Msg_ErrorLoadingSetting {
            get {
                return ResourceManager.GetString("Msg_ErrorLoadingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Critical login error. Check logs for details.
        /// </summary>
        public static string Msg_ErrorLoginFailed {
            get {
                return ResourceManager.GetString("Msg_ErrorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while database creation. Check logs.
        /// </summary>
        public static string Msg_ErrorSetupFailed {
            get {
                return ResourceManager.GetString("Msg_ErrorSetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file could not be saved. It may be open in another program, or the program does not have write permissions.
        /// </summary>
        public static string Msg_ExportError {
            get {
                return ResourceManager.GetString("Msg_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file is empty.
        /// </summary>
        public static string Msg_FileIsEmpty {
            get {
                return ResourceManager.GetString("Msg_FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Critical error during setup finish. Check logs.
        /// </summary>
        public static string Msg_FinishSetupError {
            get {
                return ResourceManager.GetString("Msg_FinishSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goal cannot be empty!.
        /// </summary>
        public static string Msg_GoalEmpty {
            get {
                return ResourceManager.GetString("Msg_GoalEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goal in the file is empty..
        /// </summary>
        public static string Msg_GoalIsEmptyImportError {
            get {
                return ResourceManager.GetString("Msg_GoalIsEmptyImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All current records will be deleted and replaced with the data from the file. Are you sure?.
        /// </summary>
        public static string Msg_ImportConfirmation {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while import. Check logs.
        /// </summary>
        public static string Msg_ImportCsvError {
            get {
                return ResourceManager.GetString("Msg_ImportCsvError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No records to export.
        /// </summary>
        public static string Msg_NoEntriesToExportError {
            get {
                return ResourceManager.GetString("Msg_NoEntriesToExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The selected file was not found..
        /// </summary>
        public static string Msg_NoFIleError {
            get {
                return ResourceManager.GetString("Msg_NoFIleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goal not set. Set a goal before exporting.
        /// </summary>
        public static string Msg_NoGoalToExportError {
            get {
                return ResourceManager.GetString("Msg_NoGoalToExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password changed successfully.
        /// </summary>
        public static string Msg_PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("Msg_PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database password removed successfully.
        /// </summary>
        public static string Msg_PasswordRemovedSuccess {
            get {
                return ResourceManager.GetString("Msg_PasswordRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password set successfully.
        /// </summary>
        public static string Msg_PasswordSetSuccess {
            get {
                return ResourceManager.GetString("Msg_PasswordSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record saved!.
        /// </summary>
        public static string Msg_RecordSaved {
            get {
                return ResourceManager.GetString("Msg_RecordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to remove the database password? Your data will no longer be encrypted.
        /// </summary>
        public static string Msg_RemovePasswordConfirmation {
            get {
                return ResourceManager.GetString("Msg_RemovePasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save entry. Check logs.
        /// </summary>
        public static string Msg_SaveEntryError {
            get {
                return ResourceManager.GetString("Msg_SaveEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fatal error while saving settings! Check logs.
        /// </summary>
        public static string Msg_SaveSettingsError {
            get {
                return ResourceManager.GetString("Msg_SaveSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings saved.
        /// </summary>
        public static string Msg_SettingsSaved {
            get {
                return ResourceManager.GetString("Msg_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export completed successfully!.
        /// </summary>
        public static string Msg_SuccessExportInfo {
            get {
                return ResourceManager.GetString("Msg_SuccessExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data imported successfully!
        ///Records imported: {0}.
        /// </summary>
        public static string Msg_SuccessImportInfo {
            get {
                return ResourceManager.GetString("Msg_SuccessImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to read Theme from database. Check logs.
        /// </summary>
        public static string Msg_ThemeReadError {
            get {
                return ResourceManager.GetString("Msg_ThemeReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username cannot be empty!.
        /// </summary>
        public static string Msg_UsernameEmpty {
            get {
                return ResourceManager.GetString("Msg_UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string NavBtn_Settings {
            get {
                return ResourceManager.GetString("NavBtn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        public static string NavBtn_Table {
            get {
                return ResourceManager.GetString("NavBtn_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your name.
        /// </summary>
        public static string Placeholder_EnterName {
            get {
                return ResourceManager.GetString("Placeholder_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter password.
        /// </summary>
        public static string Placeholder_EnterPass {
            get {
                return ResourceManager.GetString("Placeholder_EnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How should we call you?.
        /// </summary>
        public static string Placeholder_HowCallYou {
            get {
                return ResourceManager.GetString("Placeholder_HowCallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max 8 characters.
        /// </summary>
        public static string Placeholder_Max8Ch {
            get {
                return ResourceManager.GetString("Placeholder_Max8Ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is your main goal?.
        /// </summary>
        public static string Placeholder_WhatIsGoal {
            get {
                return ResourceManager.GetString("Placeholder_WhatIsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What did you achieve today?.
        /// </summary>
        public static string Placeholder_WhatYouAchive {
            get {
                return ResourceManager.GetString("Placeholder_WhatYouAchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partial Succes.
        /// </summary>
        public static string Result_Partial {
            get {
                return ResourceManager.GetString("Result_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relapse.
        /// </summary>
        public static string Result_Relapse {
            get {
                return ResourceManager.GetString("Result_Relapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string Result_Success {
            get {
                return ResourceManager.GetString("Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        public static string Title_Appearance {
            get {
                return ResourceManager.GetString("Title_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string Title_Confirmation {
            get {
                return ResourceManager.GetString("Title_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Password.
        /// </summary>
        public static string Title_ConfirmPassword {
            get {
                return ResourceManager.GetString("Title_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data management.
        /// </summary>
        public static string Title_DataManagement {
            get {
                return ResourceManager.GetString("Title_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day Datails.
        /// </summary>
        public static string Title_DayDatails {
            get {
                return ResourceManager.GetString("Title_DayDatails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day Description:.
        /// </summary>
        public static string Title_DayDescription {
            get {
                return ResourceManager.GetString("Title_DayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на day(s) streak.
        /// </summary>
        public static string Title_daysStreak {
            get {
                return ResourceManager.GetString("Title_daysStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Title_Description {
            get {
                return ResourceManager.GetString("Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Data.
        /// </summary>
        public static string Title_ExportData {
            get {
                return ResourceManager.GetString("Title_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import Data.
        /// </summary>
        public static string Title_ImportData {
            get {
                return ResourceManager.GetString("Title_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Title_password {
            get {
                return ResourceManager.GetString("Title_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile settings.
        /// </summary>
        public static string Title_ProfileSettings {
            get {
                return ResourceManager.GetString("Title_ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string Title_SaveChanges {
            get {
                return ResourceManager.GetString("Title_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language change.
        /// </summary>
        public static string Title_SelectLanguage {
            get {
                return ResourceManager.GetString("Title_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Title_Start {
            get {
                return ResourceManager.GetString("Title_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App theme.
        /// </summary>
        public static string Title_Theme {
            get {
                return ResourceManager.GetString("Title_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today.
        /// </summary>
        public static string Title_Today {
            get {
                return ResourceManager.GetString("Title_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string Title_username {
            get {
                return ResourceManager.GetString("Title_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome.
        /// </summary>
        public static string Title_Welcome {
            get {
                return ResourceManager.GetString("Title_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your goal.
        /// </summary>
        public static string Title_YourGoal {
            get {
                return ResourceManager.GetString("Title_YourGoal", resourceCulture);
            }
        }
    }
}
