//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressApp.WpfUI.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgressApp.WpfUI.Localization.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click on the cell.
        /// </summary>
        public static string Analytics_Heatmap_HintSelectCell {
            get {
                return ResourceManager.GetString("Analytics_Heatmap_HintSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View mode:.
        /// </summary>
        public static string Analytics_ViewMode {
            get {
                return ResourceManager.GetString("Analytics_ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatmap view.
        /// </summary>
        public static string AnalyticsMode_Heatmap {
            get {
                return ResourceManager.GetString("AnalyticsMode_Heatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table View.
        /// </summary>
        public static string AnalyticsMode_Table {
            get {
                return ResourceManager.GetString("AnalyticsMode_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgressApp .
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Btn_ChangePassword {
            get {
                return ResourceManager.GetString("Btn_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Btn_No {
            get {
                return ResourceManager.GetString("Btn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Btn_Ok {
            get {
                return ResourceManager.GetString("Btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open logs.
        /// </summary>
        public static string Btn_OpenLogs {
            get {
                return ResourceManager.GetString("Btn_OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_SaveDay {
            get {
                return ResourceManager.GetString("Btn_SaveDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Btn_SetPassword {
            get {
                return ResourceManager.GetString("Btn_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Btn_Yes {
            get {
                return ResourceManager.GetString("Btn_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Action.
        /// </summary>
        public static string Button_AddAction {
            get {
                return ResourceManager.GetString("Button_AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DataGrid_Date {
            get {
                return ResourceManager.GetString("DataGrid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string DataGrid_Result {
            get {
                return ResourceManager.GetString("DataGrid_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please try again.
        /// </summary>
        public static string Error_IncorrectPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password. Check logs.
        /// </summary>
        public static string Msg_ChangePasswordFailedError {
            get {
                return ResourceManager.GetString("Msg_ChangePasswordFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database save error. Check logs.
        /// </summary>
        public static string Msg_DbSaveWhileImportError {
            get {
                return ResourceManager.GetString("Msg_DbSaveWhileImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty!.
        /// </summary>
        public static string Msg_DescriptionEmpty {
            get {
                return ResourceManager.GetString("Msg_DescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate records found. Each record must be unique..
        /// </summary>
        public static string Msg_DuplicateRecordsImportError {
            get {
                return ResourceManager.GetString("Msg_DuplicateRecordsImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during import: The description cannot be empty. Line: {0}.
        /// </summary>
        public static string Msg_EmptyDescriptionImportError {
            get {
                return ResourceManager.GetString("Msg_EmptyDescriptionImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to import.
        /// </summary>
        public static string Msg_EntriesIsEmptyImportError {
            get {
                return ResourceManager.GetString("Msg_EntriesIsEmptyImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access error. Check logs.
        /// </summary>
        public static string Msg_ErrorDbAccessFailed {
            get {
                return ResourceManager.GetString("Msg_ErrorDbAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loading error. Check log file.
        /// </summary>
        public static string Msg_ErrorLoadingData {
            get {
                return ResourceManager.GetString("Msg_ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading heatmap data. Check logs.
        /// </summary>
        public static string Msg_ErrorLoadingHeatmapData {
            get {
                return ResourceManager.GetString("Msg_ErrorLoadingHeatmapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load settings: “{0}”. Please try again or check the database.
        /// </summary>
        public static string Msg_ErrorLoadingSetting {
            get {
                return ResourceManager.GetString("Msg_ErrorLoadingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating streak. Check logs.
        /// </summary>
        public static string Msg_ErrorLoadingStreak {
            get {
                return ResourceManager.GetString("Msg_ErrorLoadingStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical login error. Check logs for details.
        /// </summary>
        public static string Msg_ErrorLoginFailed {
            get {
                return ResourceManager.GetString("Msg_ErrorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while database creation. Check logs.
        /// </summary>
        public static string Msg_ErrorSetupFailed {
            get {
                return ResourceManager.GetString("Msg_ErrorSetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be saved. It may be open in another program, or the program does not have write permissions.
        /// </summary>
        public static string Msg_ExportError {
            get {
                return ResourceManager.GetString("Msg_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is empty.
        /// </summary>
        public static string Msg_FileIsEmpty {
            get {
                return ResourceManager.GetString("Msg_FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error during setup finish. Check logs.
        /// </summary>
        public static string Msg_FinishSetupError {
            get {
                return ResourceManager.GetString("Msg_FinishSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal cannot be empty!.
        /// </summary>
        public static string Msg_GoalEmpty {
            get {
                return ResourceManager.GetString("Msg_GoalEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal in the file is empty..
        /// </summary>
        public static string Msg_GoalIsEmptyImportError {
            get {
                return ResourceManager.GetString("Msg_GoalIsEmptyImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All current records will be deleted and replaced with the data from the file. Are you sure?.
        /// </summary>
        public static string Msg_ImportConfirmation {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while import. Check logs.
        /// </summary>
        public static string Msg_ImportCsvError {
            get {
                return ResourceManager.GetString("Msg_ImportCsvError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to export.
        /// </summary>
        public static string Msg_NoEntriesToExportError {
            get {
                return ResourceManager.GetString("Msg_NoEntriesToExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file was not found..
        /// </summary>
        public static string Msg_NoFIleError {
            get {
                return ResourceManager.GetString("Msg_NoFIleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal not set. Set a goal before exporting.
        /// </summary>
        public static string Msg_NoGoalToExportError {
            get {
                return ResourceManager.GetString("Msg_NoGoalToExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string Msg_PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("Msg_PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database password removed successfully.
        /// </summary>
        public static string Msg_PasswordRemovedSuccess {
            get {
                return ResourceManager.GetString("Msg_PasswordRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password set successfully.
        /// </summary>
        public static string Msg_PasswordSetSuccess {
            get {
                return ResourceManager.GetString("Msg_PasswordSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved!.
        /// </summary>
        public static string Msg_RecordSaved {
            get {
                return ResourceManager.GetString("Msg_RecordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the database password? Your data will no longer be encrypted.
        /// </summary>
        public static string Msg_RemovePasswordConfirmation {
            get {
                return ResourceManager.GetString("Msg_RemovePasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save entry. Check logs.
        /// </summary>
        public static string Msg_SaveEntryError {
            get {
                return ResourceManager.GetString("Msg_SaveEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error while saving settings! Check logs.
        /// </summary>
        public static string Msg_SaveSettingsError {
            get {
                return ResourceManager.GetString("Msg_SaveSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        public static string Msg_SettingsSaved {
            get {
                return ResourceManager.GetString("Msg_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed successfully!.
        /// </summary>
        public static string Msg_SuccessExportInfo {
            get {
                return ResourceManager.GetString("Msg_SuccessExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data imported successfully!
        ///Records imported: {0}.
        /// </summary>
        public static string Msg_SuccessImportInfo {
            get {
                return ResourceManager.GetString("Msg_SuccessImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read Theme from database. Check logs.
        /// </summary>
        public static string Msg_ThemeReadError {
            get {
                return ResourceManager.GetString("Msg_ThemeReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty!.
        /// </summary>
        public static string Msg_UsernameEmpty {
            get {
                return ResourceManager.GetString("Msg_UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string NavBtn_Analytics {
            get {
                return ResourceManager.GetString("NavBtn_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavBtn_Settings {
            get {
                return ResourceManager.GetString("NavBtn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string NavBtn_Table {
            get {
                return ResourceManager.GetString("NavBtn_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: learning.
        /// </summary>
        public static string Placeholder_ActionExample {
            get {
                return ResourceManager.GetString("Placeholder_ActionExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string Placeholder_EnterName {
            get {
                return ResourceManager.GetString("Placeholder_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Placeholder_EnterPass {
            get {
                return ResourceManager.GetString("Placeholder_EnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How should we call you?.
        /// </summary>
        public static string Placeholder_HowCallYou {
            get {
                return ResourceManager.GetString("Placeholder_HowCallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 8 characters.
        /// </summary>
        public static string Placeholder_Max8Ch {
            get {
                return ResourceManager.GetString("Placeholder_Max8Ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your main goal?.
        /// </summary>
        public static string Placeholder_WhatIsGoal {
            get {
                return ResourceManager.GetString("Placeholder_WhatIsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you achieve today?.
        /// </summary>
        public static string Placeholder_WhatYouAchive {
            get {
                return ResourceManager.GetString("Placeholder_WhatYouAchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string Range_AllTime {
            get {
                return ResourceManager.GetString("Range_AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Range_Month {
            get {
                return ResourceManager.GetString("Range_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Range_Week {
            get {
                return ResourceManager.GetString("Range_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Succes.
        /// </summary>
        public static string Result_Partial {
            get {
                return ResourceManager.GetString("Result_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relapse.
        /// </summary>
        public static string Result_Relapse {
            get {
                return ResourceManager.GetString("Result_Relapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Result_Success {
            get {
                return ResourceManager.GetString("Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks a bit empty here. Start by adding your first journal entry to track your progress..
        /// </summary>
        public static string Subtitle_EmptyTable {
            get {
                return ResourceManager.GetString("Subtitle_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to reach the goal.
        /// </summary>
        public static string Title_ActionToReachGoal {
            get {
                return ResourceManager.GetString("Title_ActionToReachGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Title_Appearance {
            get {
                return ResourceManager.GetString("Title_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Title_Confirmation {
            get {
                return ResourceManager.GetString("Title_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Title_ConfirmPassword {
            get {
                return ResourceManager.GetString("Title_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data management.
        /// </summary>
        public static string Title_DataManagement {
            get {
                return ResourceManager.GetString("Title_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Description:.
        /// </summary>
        public static string Title_DayDescription {
            get {
                return ResourceManager.GetString("Title_DayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Details.
        /// </summary>
        public static string Title_DayDetails {
            get {
                return ResourceManager.GetString("Title_DayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s) streak.
        /// </summary>
        public static string Title_daysStreak {
            get {
                return ResourceManager.GetString("Title_daysStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Title_Description {
            get {
                return ResourceManager.GetString("Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries yet.
        /// </summary>
        public static string Title_EmptyTable {
            get {
                return ResourceManager.GetString("Title_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Title_ExportData {
            get {
                return ResourceManager.GetString("Title_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the goal (optional).
        /// </summary>
        public static string Title_GoalDescription {
            get {
                return ResourceManager.GetString("Title_GoalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string Title_ImportData {
            get {
                return ResourceManager.GetString("Title_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone duration (days).
        /// </summary>
        public static string Title_MilestoneDuration {
            get {
                return ResourceManager.GetString("Title_MilestoneDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Title_password {
            get {
                return ResourceManager.GetString("Title_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        public static string Title_ProfileSettings {
            get {
                return ResourceManager.GetString("Title_ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Title_SaveChanges {
            get {
                return ResourceManager.GetString("Title_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change.
        /// </summary>
        public static string Title_SelectLanguage {
            get {
                return ResourceManager.GetString("Title_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Title_Start {
            get {
                return ResourceManager.GetString("Title_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string Title_Theme {
            get {
                return ResourceManager.GetString("Title_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Title_Today {
            get {
                return ResourceManager.GetString("Title_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Title_username {
            get {
                return ResourceManager.GetString("Title_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Title_Welcome {
            get {
                return ResourceManager.GetString("Title_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x/wk.
        /// </summary>
        public static string Title_x_wk {
            get {
                return ResourceManager.GetString("Title_x/wk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your goal.
        /// </summary>
        public static string Title_YourGoal {
            get {
                return ResourceManager.GetString("Title_YourGoal", resourceCulture);
            }
        }
    }
}
